changelog:
  categories:
    - title: 🚀 Features
      labels:
        - enhancement

    - title: 🐛 Bug Fixes
      labels:
        - bug

    - title: 🧰 Maintenance
      labels:
        - maintenance

    - title: Other Changes
      labels:
        - '*'

  exclude:
    labels:
      - skip-changelog
