# SPDX-License-Identifier: MIT
# Runtime for the opt-in privileged musl native-agent integration. The Alpine
# Corretto image provides the musl JDK. The bundle must load with nothing else
# installed, so no native packages are added here.
FROM amazoncorretto:25-alpine@sha256:4955796538972099d9c7de6e31c6a259b1de65393a58b7e0996b7cc50d7d20a7
